# Generated by Django 4.2.16 on 2026-05-09 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('requisitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='delivery_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='unit_of_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.unitofmeasure'),
        ),
    ]
