# Generated by Django 4.2.16 on 2026-05-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_document',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='contract',
            name='currency',
            field=models.CharField(default='ZMW', max_length=10),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_authority_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_by_authority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_by_vendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_vendor_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
