# Generated by Django 4.2.16 on 2026-05-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contract_appeal_pending_contract_appeal_resolved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractamendment',
            name='signed_by_authority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractamendment',
            name='signed_by_supplier',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contractsecurity',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('called', 'Called'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='active', max_length=20),
        ),
    ]
