# Generated by Django 4.2.16 on 2026-05-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_invoice_document_invoice_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetallocation',
            name='entity_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='sync_source',
            field=models.CharField(blank=True, default='manual', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='budgetallocation',
            unique_together={('entity_code', 'fiscal_year')},
        ),
    ]
