# Generated by Django 4.2.16 on 2026-05-09 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_contractamendment_signed_by_authority_and_more'),
        ('finance', '0004_invoice_approval_route_invoice_erp_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceiptnote',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_notes', to='contracts.contract'),
        ),
    ]
