# Generated by Django 4.2.16 on 2026-05-08 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalMatrix',
            fields=[
                ('matrix_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('procurement_type', models.CharField(max_length=100)),
                ('value_threshold_min', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('value_threshold_max', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('approval_flow', models.JSONField(default=list, help_text='Ordered list of approval roles')),
                ('requires_zpc', models.BooleanField(default=False)),
                ('requires_legal_review', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Approval Matrix',
                'verbose_name_plural': 'Approval Matrices',
                'db_table': 'master_approval_matrix',
                'ordering': ['value_threshold_min'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dept_code', models.CharField(max_length=50, unique=True)),
                ('dept_name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('national', 'National'), ('provincial', 'Provincial'), ('district', 'District'), ('facility', 'Facility')], max_length=50)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('budget_code', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='master_data.department')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'master_department',
                'ordering': ['dept_name'],
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('fiscal_year_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year_code', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Fiscal Year',
                'verbose_name_plural': 'Fiscal Years',
                'db_table': 'master_fiscal_year',
                'ordering': ['-year_code'],
            },
        ),
        migrations.CreateModel(
            name='FundingSource',
            fields=[
                ('source_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_code', models.CharField(max_length=50, unique=True)),
                ('source_name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('government', 'Government'), ('donor', 'Donor'), ('other', 'Other')], max_length=50)),
                ('budget_reference', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Funding Source',
                'verbose_name_plural': 'Funding Sources',
                'db_table': 'master_funding_source',
                'ordering': ['source_name'],
            },
        ),
        migrations.CreateModel(
            name='RiskLibrary',
            fields=[
                ('risk_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_category', models.CharField(max_length=255)),
                ('risk_description', models.TextField()),
                ('default_mitigation', models.TextField(blank=True)),
                ('severity_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
            ],
            options={
                'verbose_name': 'Risk Library',
                'verbose_name_plural': 'Risk Libraries',
                'db_table': 'master_risk_library',
                'ordering': ['risk_category'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('uom_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uom_code', models.CharField(max_length=20, unique=True)),
                ('uom_name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Unit of Measure',
                'verbose_name_plural': 'Units of Measure',
                'db_table': 'master_unit_of_measure',
                'ordering': ['uom_name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDepartment',
            fields=[
                ('dept_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('dept_code', models.CharField(db_index=True, max_length=50)),
                ('dept_name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('national', 'National'), ('provincial', 'Provincial'), ('district', 'District'), ('facility', 'Facility')], max_length=50)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('budget_code', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent_department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master_data.department')),
            ],
            options={
                'verbose_name': 'historical Department',
                'verbose_name_plural': 'historical Departments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCommodity',
            fields=[
                ('commodity_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('commodity_code', models.CharField(db_index=True, max_length=50)),
                ('commodity_name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit_of_measure', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master_data.unitofmeasure')),
            ],
            options={
                'verbose_name': 'historical Commodity',
                'verbose_name_plural': 'historical Commodities',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('template_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('ITB', 'Invitation to Bid'), ('RFP', 'Request for Proposal'), ('RFQ', 'Request for Quotation'), ('contract', 'Contract'), ('po', 'Purchase Order')], max_length=50)),
                ('template_content', models.TextField()),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Template',
                'verbose_name_plural': 'Document Templates',
                'db_table': 'master_document_template',
                'ordering': ['template_name'],
            },
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('commodity_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commodity_code', models.CharField(max_length=50, unique=True)),
                ('commodity_name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('unit_of_measure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.unitofmeasure')),
            ],
            options={
                'verbose_name': 'Commodity',
                'verbose_name_plural': 'Commodities',
                'db_table': 'master_commodity',
                'ordering': ['commodity_name'],
            },
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=255)),
                ('requested_change', models.JSONField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved_first', 'Approved by Director Procurement'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by_first', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_approvals', to=settings.AUTH_USER_MODEL)),
                ('approved_by_second', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_approvals', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Change Request',
                'verbose_name_plural': 'Change Requests',
                'db_table': 'master_change_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
