# Generated by Django 4.2.16 on 2026-05-08 08:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationEndpoint',
            fields=[
                ('endpoint_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_name', models.CharField(max_length=255)),
                ('endpoint_url', models.URLField(max_length=500)),
                ('auth_type', models.CharField(default='api_key', max_length=50)),
                ('auth_config', models.JSONField(default=dict, help_text='Encrypted auth configuration')),
                ('timeout_seconds', models.IntegerField(default=30)),
                ('retry_count', models.IntegerField(default=5)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Integration Endpoint',
                'verbose_name_plural': 'Integration Endpoints',
                'db_table': 'int_endpoint',
                'ordering': ['system_name'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('webhook_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_system', models.CharField(max_length=255)),
                ('payload_hash', models.CharField(max_length=128)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'Webhook Delivery',
                'verbose_name_plural': 'Webhook Deliveries',
                'db_table': 'int_webhook',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncStatus',
            fields=[
                ('sync_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=100)),
                ('last_sync_time', models.DateTimeField()),
                ('sync_status', models.CharField(default='pending', max_length=20)),
                ('records_processed', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sync Status',
                'verbose_name_plural': 'Sync Statuses',
                'db_table': 'int_sync_status',
                'unique_together': {('entity_type', 'last_sync_time')},
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_method', models.CharField(max_length=10)),
                ('request_url', models.CharField(max_length=500)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integrations.integrationendpoint')),
            ],
            options={
                'verbose_name': 'Integration Log',
                'verbose_name_plural': 'Integration Logs',
                'db_table': 'int_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
