# Generated by Django 4.2.16 on 2026-05-09 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierperformance',
            name='evaluated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierperformance',
            name='improvement_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supplierperformance',
            name='needs_improvement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='bank_account_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='bank_branch',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='ceec_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='pacra_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='VendorApplicationDocument',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='suppliers.vendorapplication')),
            ],
            options={
                'verbose_name': 'Vendor Application Document',
                'verbose_name_plural': 'Vendor Application Documents',
                'db_table': 'sup_application_document',
            },
        ),
    ]
