# Generated by Django 4.2.16 on 2026-05-08 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requisitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitation',
            fields=[
                ('solicitation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sol_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('method', models.CharField(max_length=50)),
                ('closing_date', models.DateTimeField()),
                ('opening_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('published', 'Published'), ('closed', 'Closed'), ('awarded', 'Awarded'), ('cancelled', 'Cancelled')], default='draft', max_length=50)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_solicitations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_solicitations', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitations', to='requisitions.requisition')),
            ],
            options={
                'verbose_name': 'Solicitation',
                'verbose_name_plural': 'Solicitations',
                'db_table': 'sol_solicitation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SolicitationTemplate',
            fields=[
                ('template_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=50)),
                ('document_type', models.CharField(max_length=50)),
                ('template_content', models.TextField()),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Solicitation Template',
                'verbose_name_plural': 'Solicitation Templates',
                'db_table': 'sol_template',
            },
        ),
        migrations.CreateModel(
            name='SolicitationDocument',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('bidding_document', 'Bidding Document'), ('specification', 'Specification'), ('addendum', 'Addendum'), ('clarification', 'Clarification'), ('minutes', 'Minutes'), ('other', 'Other')], max_length=50)),
                ('file_path', models.CharField(max_length=500)),
                ('is_public', models.BooleanField(default=True)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('solicitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='solicitations.solicitation')),
            ],
            options={
                'verbose_name': 'Solicitation Document',
                'verbose_name_plural': 'Solicitation Documents',
                'db_table': 'sol_document',
            },
        ),
        migrations.CreateModel(
            name='EvaluationCriterion',
            fields=[
                ('criterion_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criterion_name', models.CharField(max_length=255)),
                ('criterion_type', models.CharField(choices=[('mandatory', 'Mandatory'), ('technical', 'Technical'), ('financial', 'Financial')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('minimum_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('order_index', models.IntegerField(default=0)),
                ('solicitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_criteria', to='solicitations.solicitation')),
            ],
            options={
                'verbose_name': 'Evaluation Criterion',
                'verbose_name_plural': 'Evaluation Criteria',
                'db_table': 'sol_evaluation_criterion',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='ClarificationRequest',
            fields=[
                ('clarification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('solicitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clarifications', to='solicitations.solicitation')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clarification Request',
                'verbose_name_plural': 'Clarification Requests',
                'db_table': 'sol_clarification',
                'ordering': ['-asked_at'],
            },
        ),
        migrations.CreateModel(
            name='SolicitationAddendum',
            fields=[
                ('addendum_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('addendum_number', models.IntegerField()),
                ('description', models.TextField()),
                ('reason', models.TextField(blank=True)),
                ('extended_closing_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('solicitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addenda', to='solicitations.solicitation')),
            ],
            options={
                'verbose_name': 'Solicitation Addendum',
                'verbose_name_plural': 'Solicitation Addenda',
                'db_table': 'sol_addendum',
                'ordering': ['-addendum_number'],
                'unique_together': {('solicitation', 'addendum_number')},
            },
        ),
    ]
