# Generated by Django 4.2.16 on 2026-05-09 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('solicitations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitation',
            name='budget_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='currency',
            field=models.CharField(default='ZMW', max_length=10),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.department'),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
