# Generated by Django 4.2.16 on 2026-05-08 07:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MethodOverride',
            fields=[
                ('override_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_method', models.CharField(max_length=50)),
                ('selected_method', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Method Override',
                'verbose_name_plural': 'Method Overrides',
                'db_table': 'method_override',
            },
        ),
        migrations.CreateModel(
            name='MethodRecommendation',
            fields=[
                ('recommendation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommended_method', models.CharField(choices=[('open_tender', 'Open Tendering'), ('restricted', 'Restricted Tendering'), ('simplified', 'Simplified Bidding'), ('direct', 'Direct Procurement'), ('rfq', 'Request for Quotations'), ('proposal', 'Request for Proposals'), ('competitive_dialogue', 'Competitive Dialogue')], max_length=50)),
                ('rationale', models.TextField()),
                ('regulation_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Method Recommendation',
                'verbose_name_plural': 'Method Recommendations',
                'db_table': 'method_recommendation',
            },
        ),
        migrations.CreateModel(
            name='NonOpenJustification',
            fields=[
                ('justification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('open_tender', 'Open Tendering'), ('restricted', 'Restricted Tendering'), ('simplified', 'Simplified Bidding'), ('direct', 'Direct Procurement'), ('rfq', 'Request for Quotations'), ('proposal', 'Request for Proposals'), ('competitive_dialogue', 'Competitive Dialogue')], max_length=50)),
                ('reason_code', models.CharField(choices=[('emergency', 'Emergency Procurement'), ('proprietary', 'Proprietary Rights'), ('sole_supplier', 'Sole Supplier'), ('continuity', 'Continuity of Supply'), ('below_threshold', 'Below Threshold Limit')], max_length=50)),
                ('reason_text', models.TextField()),
                ('supporting_evidence_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for ZPC Approval'), ('zpc_approved', 'Approved by ZPC'), ('rejected', 'Rejected')], default='draft', max_length=50)),
                ('zpc_approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Non-Open Procurement Justification',
                'verbose_name_plural': 'Non-Open Procurement Justifications',
                'db_table': 'method_non_open_justification',
            },
        ),
        migrations.CreateModel(
            name='PreferenceScheme',
            fields=[
                ('scheme_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheme_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('margin_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('applies_to', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Preference Scheme',
                'verbose_name_plural': 'Preference Schemes',
                'db_table': 'method_preference_scheme',
            },
        ),
        migrations.CreateModel(
            name='ProcurementMethodType',
            fields=[
                ('method_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method_name', models.CharField(max_length=255)),
                ('method_code', models.CharField(choices=[('open_tender', 'Open Tendering'), ('restricted', 'Restricted Tendering'), ('simplified', 'Simplified Bidding'), ('direct', 'Direct Procurement'), ('rfq', 'Request for Quotations'), ('proposal', 'Request for Proposals'), ('competitive_dialogue', 'Competitive Dialogue')], max_length=50, unique=True)),
                ('applicable_to', models.CharField(blank=True, max_length=255)),
                ('threshold_min', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('threshold_max', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('is_open', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Procurement Method Type',
                'verbose_name_plural': 'Procurement Method Types',
                'db_table': 'method_type',
                'ordering': ['threshold_min'],
            },
        ),
    ]
