# Generated by Django 4.2.16 on 2026-05-08 07:57

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BidDocument',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Bid Document',
                'verbose_name_plural': 'Bid Documents',
                'db_table': 'bid_document',
            },
        ),
        migrations.CreateModel(
            name='BidOpening',
            fields=[
                ('opening_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('minutes_file_path', models.CharField(blank=True, max_length=500)),
                ('witnesses', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Bid Opening',
                'verbose_name_plural': 'Bid Openings',
                'db_table': 'bid_opening',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='BidOpeningDetail',
            fields=[
                ('detail_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opened_sequence', models.IntegerField()),
                ('price_read', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('objections', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Bid Opening Detail',
                'verbose_name_plural': 'Bid Opening Details',
                'db_table': 'bid_opening_detail',
                'ordering': ['opened_sequence'],
            },
        ),
        migrations.CreateModel(
            name='BidSecurity',
            fields=[
                ('security_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('security_type', models.CharField(choices=[('bank_guarantee', 'Bank Guarantee'), ('surety_bond', 'Surety Bond'), ('cash_deposit', 'Cash Deposit')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('issuing_institution', models.CharField(max_length=255)),
                ('reference_number', models.CharField(max_length=100)),
                ('validity_date', models.DateField()),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'Bid Security',
                'verbose_name_plural': 'Bid Securities',
                'db_table': 'bid_security',
            },
        ),
        migrations.CreateModel(
            name='BidSubmission',
            fields=[
                ('bid_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_id', models.CharField(max_length=50, unique=True)),
                ('submission_timestamp', models.DateTimeField(auto_now_add=True)),
                ('bid_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('opened', 'Opened'), ('responsive', 'Responsive'), ('non_responsive', 'Non-Responsive'), ('withdrawn', 'Withdrawn'), ('awarded', 'Awarded')], default='submitted', max_length=20)),
                ('is_late', models.BooleanField(default=False)),
                ('technical_doc_url', models.URLField(blank=True)),
                ('financial_doc_url', models.URLField(blank=True, help_text='Encrypted financial document URL')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bid Submission',
                'verbose_name_plural': 'Bid Submissions',
                'db_table': 'bid_submission',
                'ordering': ['-submission_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PreBidConference',
            fields=[
                ('conference_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('attendance_list', models.JSONField(default=list)),
                ('minutes_file_path', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Pre-Bid Conference',
                'verbose_name_plural': 'Pre-Bid Conferences',
                'db_table': 'bid_pre_bid_conference',
            },
        ),
    ]
