# Generated by Django 4.2.16 on 2026-05-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidsubmission',
            name='currency',
            field=models.CharField(default='ZMW', max_length=10),
        ),
        migrations.AddField(
            model_name='bidsubmission',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidsubmission',
            name='security_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='bidsubmission',
            name='security_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidsubmission',
            name='security_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bidsubmission',
            name='security_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bidsubmission',
            name='submission_method',
            field=models.CharField(default='online', max_length=20),
        ),
        migrations.AddField(
            model_name='bidsubmission',
            name='validity_period_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
