# Generated by Django 4.2.16 on 2026-05-08 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requisitions', '0001_initial'),
        ('procurement_planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractprocurementplan',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpp', to='requisitions.requisition'),
        ),
        migrations.AddField(
            model_name='applineitem',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='procurement_planning.annualprocurementplan'),
        ),
        migrations.AddField(
            model_name='applineitem',
            name='commodity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.commodity'),
        ),
        migrations.AddField(
            model_name='applineitem',
            name='funding_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.fundingsource'),
        ),
        migrations.AddField(
            model_name='annualprocurementplan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annualprocurementplan',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.department'),
        ),
        migrations.AddField(
            model_name='annualprocurementplan',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.fiscalyear'),
        ),
        migrations.AddField(
            model_name='annualprocurementplan',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='annualprocurementplan',
            unique_together={('fiscal_year', 'department')},
        ),
    ]
