# Generated by Django 4.2.16 on 2026-05-08 08:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedProcurementFile',
            fields=[
                ('archive_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('procurement_id', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=500)),
                ('encryption_key_ref', models.CharField(blank=True, max_length=200)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('retention_expiry', models.DateField()),
                ('legal_hold', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Archived Procurement File',
                'verbose_name_plural': 'Archived Procurement Files',
                'db_table': 'rpt_archive',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementWarehouse',
            fields=[
                ('fact_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('procurement_id', models.CharField(max_length=100, unique=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('method', models.CharField(max_length=50)),
                ('award_date', models.DateField(blank=True, null=True)),
                ('supplier_category', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('processing_days', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Procurement Warehouse',
                'verbose_name_plural': 'Procurement Warehouse',
                'db_table': 'rpt_warehouse',
                'ordering': ['-award_date'],
            },
        ),
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=255)),
                ('report_type', models.CharField(max_length=50)),
                ('schedule', models.CharField(blank=True, max_length=100)),
                ('format', models.CharField(blank=True, max_length=50)),
                ('recipient_list', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Report Definition',
                'verbose_name_plural': 'Report Definitions',
                'db_table': 'rpt_definition',
            },
        ),
        migrations.CreateModel(
            name='ReportGeneration',
            fields=[
                ('generation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='reporting.reportdefinition')),
            ],
            options={
                'verbose_name': 'Report Generation',
                'verbose_name_plural': 'Report Generations',
                'db_table': 'rpt_generation',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('forecast_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=50)),
                ('forecast_period', models.CharField(max_length=20)),
                ('forecasted_quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('upper_bound', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('lower_bound', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Demand Forecast',
                'verbose_name_plural': 'Demand Forecasts',
                'db_table': 'rpt_demand_forecast',
                'unique_together': {('item_code', 'forecast_period')},
            },
        ),
    ]
