# Generated by Django 4.2.16 on 2026-05-09 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZPPASubmission',
            fields=[
                ('submission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for Submission'), ('submitted', 'Submitted to ZPPA'), ('acknowledged', 'Acknowledged by ZPPA'), ('rejected', 'Rejected by ZPPA')], default='draft', max_length=20)),
                ('response_message', models.TextField(blank=True)),
                ('zppa_reference', models.CharField(blank=True, max_length=100)),
                ('submission_data', models.JSONField(blank=True, default=dict)),
                ('generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zppa_submissions', to='reporting.reportgeneration')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zppa_submissions', to='reporting.reportdefinition')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ZPPA Submission',
                'verbose_name_plural': 'ZPPA Submissions',
                'db_table': 'rpt_zppa_submission',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
