# Generated by Django 4.2.16 on 2026-05-08 08:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0002_initial'),
        ('suppliers', '0001_initial'),
        ('requisitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('allocation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_level', models.CharField(max_length=50)),
                ('entity_code', models.CharField(max_length=50)),
                ('fiscal_year', models.CharField(max_length=20)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('encumbered_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('expended_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
            options={
                'verbose_name': 'Budget Allocation',
                'verbose_name_plural': 'Budget Allocations',
                'db_table': 'fin_budget_allocation',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po_number', models.CharField(blank=True, max_length=50)),
                ('invoice_number', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_matching', 'Pending 3-Way Match'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved for Payment'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='draft', max_length=50)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='contracts.contract')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'fin_invoice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreeWayMatch',
            fields=[
                ('match_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po_quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('grn_quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('invoice_quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('po_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('invoice_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('match_status', models.CharField(choices=[('complete', 'Complete Match'), ('partial', 'Partial Match'), ('no_match', 'No Match')], max_length=20)),
                ('discrepancies', models.JSONField(blank=True, default=dict)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='three_way_matches', to='finance.invoice')),
            ],
            options={
                'verbose_name': '3-Way Match',
                'verbose_name_plural': '3-Way Matches',
                'db_table': 'fin_3way_match',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payment_method', models.CharField(choices=[('electronic', 'Electronic Funds Transfer'), ('cheque', 'Cheque'), ('loc', 'Letter of Credit'), ('iso20022', 'ISO 20022 Transfer')], max_length=20)),
                ('iso20022_file_ref', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent to Bank'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.invoice')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'fin_payment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LetterOfCredit',
            fields=[
                ('loc_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loc_type', models.CharField(choices=[('sight', 'Sight LC'), ('usance', 'Usance LC'), ('standby', 'Standby LC')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('issuing_bank', models.CharField(max_length=255)),
                ('beneficiary', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('confirmed', 'Confirmed'), ('utilized', 'Partially Utilized'), ('exhausted', 'Exhausted'), ('expired', 'Expired')], default='issued', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters_of_credit', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Letter of Credit',
                'verbose_name_plural': 'Letters of Credit',
                'db_table': 'fin_loc',
            },
        ),
        migrations.CreateModel(
            name='BudgetEncumbrance',
            fields=[
                ('encumbrance_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('erp_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_encumbrances', to='requisitions.requisition')),
            ],
            options={
                'verbose_name': 'Budget Encumbrance',
                'verbose_name_plural': 'Budget Encumbrances',
                'db_table': 'fin_encumbrance',
            },
        ),
    ]
