# Generated by Django 4.2.16 on 2026-05-09 09:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_contractamendment_signed_by_authority_and_more'),
        ('finance', '0003_budgetallocation_entity_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='approval_route',
            field=models.CharField(blank=True, choices=[('finance_officer', 'Finance Officer'), ('department_head', 'Department Head'), ('director_general', 'Director General')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='erp_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='erp_posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_advice_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_advice_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='GoodsReceiptNote',
            fields=[
                ('grn_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po_number', models.CharField(blank=True, default='', max_length=50)),
                ('grn_number', models.CharField(max_length=100, unique=True)),
                ('item_description', models.TextField(blank=True, default='')),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('source', models.CharField(default='webhook', help_text='webhook, manual, api', max_length=50)),
                ('raw_webhook', models.JSONField(blank=True, default=dict)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_notes', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Goods Receipt Note',
                'verbose_name_plural': 'Goods Receipt Notes',
                'db_table': 'fin_grn',
                'ordering': ['-received_date'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='grn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='finance.goodsreceiptnote'),
        ),
    ]
