# Generated by Django 4.2.16 on 2026-05-08 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('tin', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('ceec_category', models.CharField(choices=[('citizen_influenced', 'Citizen-Influenced'), ('citizen_empowered', 'Citizen-Empowered'), ('citizen_owned', 'Citizen-Owned'), ('non_citizen', 'Non-Citizen')], default='non_citizen', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Registration'), ('active', 'Active'), ('suspended', 'Suspended'), ('debarred', 'Debarred')], default='pending', max_length=20)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'sup_supplier',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VendorApplication',
            fields=[
                ('application_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=50)),
                ('tin', models.CharField(max_length=50)),
                ('ceec_certificate_number', models.CharField(blank=True, max_length=100)),
                ('ceec_category', models.CharField(choices=[('citizen_influenced', 'Citizen-Influenced'), ('citizen_empowered', 'Citizen-Empowered'), ('citizen_owned', 'Citizen-Owned'), ('non_citizen', 'Non-Citizen')], max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('pending_pacra', 'Pending PACRA Verification'), ('pending_ceec', 'Pending CEEC Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Application',
                'verbose_name_plural': 'Vendor Applications',
                'db_table': 'sup_application',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierRiskScore',
            fields=[
                ('risk_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('factors', models.JSONField(default=dict)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Risk Score',
                'verbose_name_plural': 'Supplier Risk Scores',
                'db_table': 'sup_risk_score',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPerformance',
            fields=[
                ('performance_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evaluation_date', models.DateField()),
                ('metrics', models.JSONField(default=dict)),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_performances', to='contracts.contract')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Performance',
                'verbose_name_plural': 'Supplier Performances',
                'db_table': 'sup_performance',
                'ordering': ['-evaluation_date'],
            },
        ),
        migrations.CreateModel(
            name='SupplierDocument',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=500)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Document',
                'verbose_name_plural': 'Supplier Documents',
                'db_table': 'sup_document',
            },
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('blacklist_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tin', models.CharField(blank=True, max_length=50)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('reason', models.TextField()),
                ('debarred_until', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_entries', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Blacklist',
                'verbose_name_plural': 'Blacklists',
                'db_table': 'sup_blacklist',
                'ordering': ['-created_at'],
            },
        ),
    ]
