# Generated by Django 4.2.16 on 2026-05-08 07:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidEvaluationReport',
            fields=[
                ('ber_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_content', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bid Evaluation Report',
                'verbose_name_plural': 'Bid Evaluation Reports',
                'db_table': 'eval_ber',
            },
        ),
        migrations.CreateModel(
            name='CombinedScore',
            fields=[
                ('combined_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('technical_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('financial_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rank', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Combined Score',
                'verbose_name_plural': 'Combined Scores',
                'db_table': 'eval_combined_score',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationCommittee',
            fields=[
                ('committee_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('members', models.JSONField(default=list)),
                ('formed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evaluation Committee',
                'verbose_name_plural': 'Evaluation Committees',
                'db_table': 'eval_committee',
            },
        ),
        migrations.CreateModel(
            name='FinancialEvaluation',
            fields=[
                ('evaluation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('corrected_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('currency_converted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('preference_applied', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('evaluated_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('financial_score', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Financial Evaluation',
                'verbose_name_plural': 'Financial Evaluations',
                'db_table': 'eval_financial',
            },
        ),
        migrations.CreateModel(
            name='PostQualification',
            fields=[
                ('pq_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_items', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Post Qualification',
                'verbose_name_plural': 'Post Qualifications',
                'db_table': 'eval_post_qualification',
            },
        ),
        migrations.CreateModel(
            name='PreliminaryExam',
            fields=[
                ('exam_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criterion', models.CharField(max_length=255)),
                ('is_compliant', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Preliminary Examination',
                'verbose_name_plural': 'Preliminary Examinations',
                'db_table': 'eval_preliminary_exam',
            },
        ),
        migrations.CreateModel(
            name='TechnicalScore',
            fields=[
                ('score_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weighted_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_scores', to='bids.bidsubmission')),
            ],
            options={
                'verbose_name': 'Technical Score',
                'verbose_name_plural': 'Technical Scores',
                'db_table': 'eval_technical_score',
            },
        ),
    ]
