# Generated by Django 4.2.16 on 2026-05-08 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
        ('solicitations', '0001_initial'),
        ('bids', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalscore',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitations.evaluationcriterion'),
        ),
        migrations.AddField(
            model_name='technicalscore',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preliminaryexam',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preliminary_exams', to='bids.bidsubmission'),
        ),
        migrations.AddField(
            model_name='postqualification',
            name='ber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_qualifications', to='evaluations.bidevaluationreport'),
        ),
        migrations.AddField(
            model_name='postqualification',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.bidsubmission'),
        ),
        migrations.AddField(
            model_name='financialevaluation',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_evaluations', to='bids.bidsubmission'),
        ),
        migrations.AddField(
            model_name='evaluationcommittee',
            name='chairperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chaired_committees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluationcommittee',
            name='secretary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretary_committees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluationcommittee',
            name='solicitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_committees', to='solicitations.solicitation'),
        ),
        migrations.AddField(
            model_name='combinedscore',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combined_scores', to='bids.bidsubmission'),
        ),
        migrations.AddField(
            model_name='bidevaluationreport',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ber_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bidevaluationreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ber_creators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bidevaluationreport',
            name='solicitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_reports', to='solicitations.solicitation'),
        ),
        migrations.AlterUniqueTogether(
            name='technicalscore',
            unique_together={('bid', 'evaluator', 'criterion')},
        ),
    ]
