# Generated by Django 4.2.16 on 2026-05-09 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalscore',
            name='is_final',
            field=models.BooleanField(default=False, help_text='True once all evaluators have scored this bid'),
        ),
        migrations.CreateModel(
            name='ConflictOfInterest',
            fields=[
                ('coi_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('declaration', models.TextField(blank=True, help_text='Details of the conflict or reason for declaration')),
                ('has_conflict', models.BooleanField(default=False)),
                ('recused', models.BooleanField(default=False, help_text='Auto-set to True when has_conflict=True')),
                ('declared_at', models.DateTimeField(auto_now_add=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_declarations', to='evaluations.evaluationcommittee')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coi_declarations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conflict of Interest',
                'verbose_name_plural': 'Conflicts of Interest',
                'db_table': 'eval_coi',
                'unique_together': {('committee', 'member')},
            },
        ),
    ]
