# Generated by Django 4.2.16 on 2026-05-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_technicalscore_is_final_conflictofinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialevaluation',
            name='arithmetic_corrections',
            field=models.JSONField(blank=True, default=list, help_text='List of {line_item, unit_price, quantity, stated_total, corrected_total}'),
        ),
        migrations.AddField(
            model_name='financialevaluation',
            name='conversion_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='financialevaluation',
            name='preference_category',
            field=models.CharField(choices=[('0', '0% (No Preference)'), ('4', '4%'), ('8', '8%'), ('12', '12%'), ('15', '15%')], default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='financialevaluation',
            name='source_currency',
            field=models.CharField(default='ZMW', max_length=10),
        ),
    ]
