# Generated by Django 4.2.16 on 2026-05-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_financialevaluation_arithmetic_corrections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidevaluationreport',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bidevaluationreport',
            name='signatures',
            field=models.JSONField(blank=True, default=list, help_text='List of {member_id, member_name, signed_at, role}'),
        ),
    ]
