# Generated by Django 4.2.16 on 2026-05-08 07:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationEndpoint',
            fields=[
                ('endpoint_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_name', models.CharField(max_length=255)),
                ('endpoint_url', models.URLField(max_length=500)),
                ('auth_type', models.CharField(default='api_key', max_length=50)),
                ('auth_config', models.JSONField(default=dict, help_text='Encrypted authentication configuration')),
                ('timeout_seconds', models.IntegerField(default=30)),
                ('retry_count', models.IntegerField(default=3)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Integration Endpoint',
                'verbose_name_plural': 'Integration Endpoints',
                'db_table': 'config_integration_endpoint',
                'ordering': ['system_name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('template_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_key', models.CharField(max_length=100, unique=True)),
                ('subject_template', models.CharField(max_length=255)),
                ('body_template', models.TextField(help_text='HTML body template')),
                ('placeholders', models.JSONField(default=list, help_text='List of placeholder keys')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'db_table': 'config_notification_template',
                'ordering': ['template_key'],
            },
        ),
        migrations.CreateModel(
            name='PreferenceRule',
            fields=[
                ('preference_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preference_key', models.CharField(max_length=100, unique=True)),
                ('preference_name', models.CharField(max_length=255)),
                ('value', models.JSONField()),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Preference Rule',
                'verbose_name_plural': 'Preference Rules',
                'db_table': 'config_preference_rule',
                'ordering': ['preference_key'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255)),
                ('task_type', models.CharField(max_length=100)),
                ('schedule_cron', models.CharField(blank=True, max_length=100)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Scheduled Task',
                'verbose_name_plural': 'Scheduled Tasks',
                'db_table': 'config_scheduled_task',
                'ordering': ['task_name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('setting_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('setting_key', models.CharField(max_length=100, unique=True)),
                ('setting_value', models.JSONField()),
                ('data_type', models.CharField(default='string', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_encrypted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'db_table': 'config_system_setting',
                'ordering': ['category', 'setting_key'],
            },
        ),
        migrations.CreateModel(
            name='ThresholdRule',
            fields=[
                ('rule_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_key', models.CharField(max_length=100, unique=True)),
                ('rule_name', models.CharField(max_length=255)),
                ('min_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('currency', models.CharField(default='ZMW', max_length=10)),
                ('applies_to', models.CharField(help_text='Entity type this rule applies to', max_length=100)),
                ('default_method', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Threshold Rule',
                'verbose_name_plural': 'Threshold Rules',
                'db_table': 'config_threshold_rule',
                'ordering': ['min_value'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('stage_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_name', models.CharField(max_length=100)),
                ('stage_order', models.IntegerField()),
                ('stage_name', models.CharField(max_length=255)),
                ('stage_code', models.CharField(max_length=50)),
                ('allowed_actions', models.JSONField(default=list)),
                ('allowed_roles', models.JSONField(default=list)),
                ('time_limit_hours', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Workflow Stage',
                'verbose_name_plural': 'Workflow Stages',
                'db_table': 'config_workflow_stage',
                'ordering': ['workflow_name', 'stage_order'],
                'unique_together': {('workflow_name', 'stage_order')},
            },
        ),
    ]
