# Generated by Django 4.2.16 on 2026-05-08 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('requisition_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('req_number', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('estimated_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('required_date', models.DateField()),
                ('delivery_location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_dept_head', 'Pending Department Head Approval'), ('pending_finance', 'Pending Finance Validation'), ('pending_dg', 'Pending Director General Approval'), ('pending_zpc', 'Pending ZPC Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('amended', 'Amended')], default='draft', max_length=50)),
                ('budget_validated', models.BooleanField(default=False)),
                ('encumbrance_ref', models.CharField(blank=True, max_length=100)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_approvals', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.department')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requisition',
                'verbose_name_plural': 'Requisitions',
                'db_table': 'req_requisition',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('specification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specification_type', models.CharField(choices=[('goods', 'Goods Specification'), ('tor', 'Terms of Reference'), ('sow', 'Scope of Work')], max_length=20)),
                ('content', models.JSONField()),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='requisitions.requisition')),
            ],
            options={
                'verbose_name': 'Specification',
                'verbose_name_plural': 'Specifications',
                'db_table': 'req_specification',
            },
        ),
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit_price_estimate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_estimate', models.DecimalField(decimal_places=2, editable=False, max_digits=20)),
                ('commodity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.commodity')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='requisitions.requisition')),
                ('unit_of_measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.unitofmeasure')),
            ],
            options={
                'verbose_name': 'Requisition Item',
                'verbose_name_plural': 'Requisition Items',
                'db_table': 'req_requisition_item',
            },
        ),
        migrations.CreateModel(
            name='RequisitionApproval',
            fields=[
                ('approval_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_level', models.CharField(max_length=50)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned for Revision')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='requisitions.requisition')),
            ],
            options={
                'verbose_name': 'Requisition Approval',
                'verbose_name_plural': 'Requisition Approvals',
                'db_table': 'req_approval',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalRequisitionItem',
            fields=[
                ('item_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('item_code', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit_price_estimate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_estimate', models.DecimalField(decimal_places=2, editable=False, max_digits=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('commodity', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master_data.commodity')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='requisitions.requisition')),
                ('unit_of_measure', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master_data.unitofmeasure')),
            ],
            options={
                'verbose_name': 'historical Requisition Item',
                'verbose_name_plural': 'historical Requisition Items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BudgetEncumbrance',
            fields=[
                ('encumbrance_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('erp_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('converted', 'Converted to PO')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encumbrances', to='requisitions.requisition')),
            ],
            options={
                'verbose_name': 'Budget Encumbrance',
                'verbose_name_plural': 'Budget Encumbrances',
                'db_table': 'req_encumbrance',
            },
        ),
        migrations.CreateModel(
            name='RequisitionVersion',
            fields=[
                ('version_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('data_snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='requisitions.requisition')),
            ],
            options={
                'verbose_name': 'Requisition Version',
                'verbose_name_plural': 'Requisition Versions',
                'db_table': 'req_version',
                'ordering': ['-version_number'],
                'unique_together': {('requisition', 'version_number')},
            },
        ),
    ]
