# Generated by Django 4.2.16 on 2026-05-08 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bids', '0001_initial'),
        ('solicitations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prebidconference',
            name='solicitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_bid_conferences', to='solicitations.solicitation'),
        ),
        migrations.AddField(
            model_name='bidsubmission',
            name='solicitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='solicitations.solicitation'),
        ),
        migrations.AddField(
            model_name='bidsubmission',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bidsecurity',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_securities', to='bids.bidsubmission'),
        ),
        migrations.AddField(
            model_name='bidopeningdetail',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.bidsubmission'),
        ),
        migrations.AddField(
            model_name='bidopeningdetail',
            name='opening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_details', to='bids.bidopening'),
        ),
        migrations.AddField(
            model_name='bidopening',
            name='conducted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bidopening',
            name='solicitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_openings', to='solicitations.solicitation'),
        ),
        migrations.AddField(
            model_name='biddocument',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_documents', to='bids.bidsubmission'),
        ),
        migrations.AlterUniqueTogether(
            name='bidsubmission',
            unique_together={('solicitation', 'supplier')},
        ),
    ]
