# Generated by Django 4.2.16 on 2026-05-08 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluations', '0002_initial'),
        ('solicitations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(max_length=50, unique=True)),
                ('contract_type', models.CharField(choices=[('po', 'Purchase Order'), ('exc', 'Framework Contract')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_acceptance', 'Pending Supplier Acceptance'), ('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated'), ('cancelled', 'Cancelled')], default='draft', max_length=50)),
                ('award_date', models.DateField(blank=True, null=True)),
                ('acceptance_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='evaluations.bidevaluationreport')),
                ('contract_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_contracts', to=settings.AUTH_USER_MODEL)),
                ('solicitation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='solicitations.solicitation')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'db_table': 'cnt_contract',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiquidatedDamages',
            fields=[
                ('ld_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessment_date', models.DateField()),
                ('days_delayed', models.IntegerField()),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('calculated_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('applied_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('assessed', 'Assessed'), ('waived', 'Waived'), ('applied', 'Applied')], default='assessed', max_length=20)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidated_damages', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Liquidated Damages',
                'verbose_name_plural': 'Liquidated Damages',
                'db_table': 'cnt_ld',
            },
        ),
        migrations.CreateModel(
            name='ContractTermination',
            fields=[
                ('termination_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('termination_type', models.CharField(choices=[('mutual', 'Mutual Agreement'), ('default', 'Supplier Default'), ('convenience', 'Convenience of the Agency'), ('force_majeure', 'Force Majeure')], max_length=50)),
                ('effective_date', models.DateField()),
                ('reason', models.TextField()),
                ('legal_review_ref', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminations', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Contract Termination',
                'verbose_name_plural': 'Contract Terminations',
                'db_table': 'cnt_termination',
            },
        ),
        migrations.CreateModel(
            name='ContractSecurity',
            fields=[
                ('security_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('security_type', models.CharField(choices=[('performance', 'Performance Bond'), ('advance', 'Advance Payment Guarantee')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('issuing_bank', models.CharField(max_length=255)),
                ('reference_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('called', 'Called'), ('expired', 'Expired')], default='active', max_length=20)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='securities', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Contract Security',
                'verbose_name_plural': 'Contract Securities',
                'db_table': 'cnt_security',
            },
        ),
        migrations.CreateModel(
            name='ContractMilestone',
            fields=[
                ('milestone_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('milestone_name', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Contract Milestone',
                'verbose_name_plural': 'Contract Milestones',
                'db_table': 'cnt_milestone',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractAmendment',
            fields=[
                ('amendment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amendment_number', models.IntegerField()),
                ('reason', models.TextField()),
                ('description', models.TextField()),
                ('financial_impact', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('variation_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('legal_review_required', models.BooleanField(default=False)),
                ('legal_opinion_ref', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Contract Amendment',
                'verbose_name_plural': 'Contract Amendments',
                'db_table': 'cnt_amendment',
                'ordering': ['-amendment_number'],
            },
        ),
    ]
