# Generated by Django 4.2.16 on 2026-05-08 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
        ('contracts', '0001_initial'),
        ('bids', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='contract',
            name='winning_bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='bids.bidsubmission'),
        ),
        migrations.AlterUniqueTogether(
            name='contractamendment',
            unique_together={('contract', 'amendment_number')},
        ),
    ]
