# Generated by Django 4.2.16 on 2026-05-09 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0003_contract_contract_document_contract_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='appeal_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='appeal_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='award_notice_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='award_notice_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='legal_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='performance_security_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='performance_security_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='performance_security_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='retention_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='waiting_period_days',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='contract',
            name='waiting_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='waiting_period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_acceptance', 'Pending Supplier Acceptance'), ('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated'), ('cancelled', 'Cancelled'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=50),
        ),
        migrations.CreateModel(
            name='ClosureChecklist',
            fields=[
                ('checklist_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('all_deliverables_received', models.BooleanField(default=False)),
                ('final_inspection_passed', models.BooleanField(default=False)),
                ('all_payments_processed', models.BooleanField(default=False)),
                ('performance_security_released', models.BooleanField(default=False)),
                ('snagging_items_resolved', models.BooleanField(default=False)),
                ('staff_warranty_training_done', models.BooleanField(default=False)),
                ('as_built_docs_received', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closure_checklists', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_checklists', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Closure Checklist',
                'verbose_name_plural': 'Closure Checklists',
                'db_table': 'cnt_closure_checklist',
            },
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('appeal_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grounds', models.TextField()),
                ('supporting_docs', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('filed', 'Filed'), ('under_review', 'Under Review'), ('upheld', 'Upheld'), ('dismissed', 'Dismissed')], default='filed', max_length=20)),
                ('filed_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='contracts.contract')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeal_resolutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appeal',
                'verbose_name_plural': 'Appeals',
                'db_table': 'cnt_appeal',
                'ordering': ['-filed_at'],
            },
        ),
    ]
