# Generated by Django 4.2.16 on 2026-05-09 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_bidsubmission_currency_bidsubmission_opened_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddocument',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bidsubmission',
            name='addenda_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bidsubmission',
            name='addenda_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidsubmission',
            name='financial_envelope_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bidsubmission',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='biddocument',
            name='document_type',
            field=models.CharField(choices=[('technical_proposal', 'Technical Proposal'), ('financial_proposal', 'Financial Proposal'), ('bid_security', 'Bid Security'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bidsubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('opened', 'Opened'), ('responsive', 'Responsive'), ('non_responsive', 'Non-Responsive'), ('withdrawn', 'Withdrawn'), ('awarded', 'Awarded')], default='submitted', max_length=20),
        ),
    ]
