# Generated by Django 4.2.16 on 2026-05-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_biddocument_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidopening',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='bidopening',
            name='witness_signatures',
            field=models.JSONField(blank=True, default=list, help_text='List of {name, role, signed_at, signature_ref}'),
        ),
        migrations.AddField(
            model_name='bidopeningdetail',
            name='bidder_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bidopeningdetail',
            name='financial_sealed',
            field=models.BooleanField(default=True, help_text='True = financial envelope not yet opened (two-envelope system)'),
        ),
    ]
