# Generated by Django 4.2.16 on 2026-05-09 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procurement_planning', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualprocurementplan',
            name='approval_trail',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='annualprocurementplan',
            name='compliance_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='annualprocurementplan',
            name='consolidated_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consolidated_from', to='procurement_planning.annualprocurementplan'),
        ),
        migrations.AddField(
            model_name='annualprocurementplan',
            name='consolidation_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='annualprocurementplan',
            name='is_consolidated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annualprocurementplan',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualprocurementplan',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_rejections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annualprocurementplan',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='annualprocurementplan',
            name='zpc_resolution',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='generalprocurementnotice',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_gpns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generalprocurementnotice',
            name='publication_targets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='generalprocurementnotice',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalprocurementnotice',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_gpns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='generalprocurementnotice',
            name='publication_proof_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
