# Generated by Django 4.2.16 on 2026-05-09 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0002_alter_requisition_delivery_location_and_more'),
        ('solicitations', '0002_solicitation_budget_code_solicitation_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitation',
            name='opening_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitations', to='requisitions.requisition'),
        ),
    ]
