# Generated by Django 4.2.16 on 2026-05-08 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualProcurementPlan',
            fields=[
                ('app_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('dept_head_review', 'Department Head Review'), ('procurement_review', 'Procurement Review'), ('director_review', 'Director of Procurement Review'), ('zpc_review', 'ZPC Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published')], default='draft', max_length=50)),
                ('total_estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Annual Procurement Plan',
                'verbose_name_plural': 'Annual Procurement Plans',
                'db_table': 'proc_annual_plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APPLineItem',
            fields=[
                ('line_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('recommended_method', models.CharField(blank=True, max_length=50)),
                ('planned_issue_date', models.DateField(blank=True, null=True)),
                ('planned_award_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'APP Line Item',
                'verbose_name_plural': 'APP Line Items',
                'db_table': 'proc_app_line_item',
            },
        ),
        migrations.CreateModel(
            name='ContractProcurementPlan',
            fields=[
                ('cpp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('procurement_strategy', models.CharField(blank=True, max_length=255)),
                ('milestones', models.JSONField(default=list)),
                ('resource_requirements', models.JSONField(default=dict)),
                ('risk_assessment', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract Procurement Plan',
                'verbose_name_plural': 'Contract Procurement Plans',
                'db_table': 'proc_contract_plan',
            },
        ),
        migrations.CreateModel(
            name='ProcurementMilestone',
            fields=[
                ('milestone_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('milestone_name', models.CharField(max_length=255)),
                ('planned_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('variance_days', models.IntegerField(blank=True, null=True)),
                ('cpp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_milestones', to='procurement_planning.contractprocurementplan')),
            ],
            options={
                'verbose_name': 'Procurement Milestone',
                'verbose_name_plural': 'Procurement Milestones',
                'db_table': 'proc_milestone',
                'ordering': ['planned_date'],
            },
        ),
        migrations.CreateModel(
            name='GeneralProcurementNotice',
            fields=[
                ('gpn_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.JSONField(default=dict)),
                ('publication_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=50)),
                ('publication_proof_urls', models.JSONField(default=list)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpns', to='procurement_planning.annualprocurementplan')),
            ],
            options={
                'verbose_name': 'General Procurement Notice',
                'verbose_name_plural': 'General Procurement Notices',
                'db_table': 'proc_gpn',
            },
        ),
    ]
